# Generated by Django 3.1.4 on 2020-12-28 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start', models.DateField()),
                ('booking_end', models.DateField()),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.cabinet')),
            ],
        ),
    ]
