# Generated by Django 3.1.4 on 2020-12-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
